title: CSS Advanced 2019
email: mgospodinov1978@gmail.com
description: Hi there!
destination: docs
baseurl: "" 
url: "" 
twitter_username: gospod1978
github_username:  gospod1978
# Build settings
theme: 
plugins:
  - jekyll-feed

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
